
export const productsListConstants = {
  SET_IS_LIST_PAGE: "SET_IS_LIST_PAGE",
  GET_FILTER_CATEGORY_OPTIONS: "GET_FILTER_CATEGORY_OPTIONS",
  ADD_CATEGORIES_FILTER: "ADD_CATEGORIES_FILTER",
  SET_QUERY: "SET_QUERY",
  SET_PAGE_NUMBER: "SET_PAGE_NUMBER",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PENDING: "SET_PENDING",
  SET_ERROR: "SET_ERROR",
  SET_LIKE: "SET_LIKE",
  SET_INITIAL_LIKES: "SET_INITIAL_LIKES",
  SET_FAVORITES: "SET_FAVORITES",
  TOGGLE_HIDE_STATUS: "TOGGLE_HIDE_STATUS",
  PATCH_PRODUCT: "PATCH_PRODUCT"
};
